
export const UPDATE_GUESSED_ALPHABETS = 'UPDATE_GUESSED_ALPHABETS'
export const UPDATE_MOVES_PLAYED = 'UPDATE_MOVES_PLAYED'
export const UPDATE_IMAGE_IDX = 'UPDATE_IMAGE_IDX'
export const UPDATE_GAME_END = 'UPDATE_GAME_END'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const RESET_GAME= 'RESET_GAME'
export const UPDATE_SECRET_WORD = 'UPDATE_SECRET_WORD'