export const sports = [
    'SOCCER',
    'BASKETBALL',
    'TENNIS',
    'BASEBALL',
    'GOLF',
    'RUNNING',
    'VOLLEYBALL',
    'BADMINTON',
    'SWIMMING',
    'BOXING',
    'TABLE TENNIS',
    'SKIING',
    'ICE SKATING',
    'ROLLER SKATING',
    'CRICKET',
    'RUGBY',
    'POOL',
    'DARTS',
    'FOOTBALL',
    'BOWLING',
    'ICE HOCKEY',
    'SURFING',
    'KARATE',
    'HORSE RACING',
    'SNOWBOARDING',
    'SKATEBOARDING',
    'CYCLING',
    'ARCHERY',
    'FISHING',
    'GYMNASTICS',
    'FIGURE SKATING',
    'ROCK CLIMBING',
    'SUMO WRESTLING',
    'TAEKWONDO',
    'FENCING',
    'WATER SKIING',
    'JET SKIING',
    'WEIGHT LIFTING',
    'SCUBA DIVING',
    'JUDO',
    'WIND SURFING',
    'KICKBOXING',
    'SKY DIVING',
    'HANG GLIDING',
    'BUNGEE JUMPING',
]

export const animals = [
    'ALLIGATOR',
    'BEAR',
    'CHEETAH',
    'DEER',
    'ELEPHANT',
    'FOX',
    'GIRAFFE',
    'HIPPO',
    'JAGUAR',
    'KANGAROO',
    'LION',
    'MONKEY',
    'PENGUIN',
    'RABBIT',
    'SHARK',
    'TIGER',
    'WOLF',
    'YAK',
    'ZEBRA'
]

export const countries = [
    'CHINA',
    'INDIA',
    'UNITED STATES',
    'INDONESIA',
    'PAKISTAN',
    'BRAZIL',
    'NIGERIA',
    'BANGLADESH',
    'RUSSIA',
    'MEXICO',
    'JAPAN',
    'ETHIOPIA',
    'PHILIPPINES',
    'EGYPT',
    'VIETNAM',
    'DR CONGO',
    'TURKEY',
    'IRAN',
    'GERMANY',
    'THAILAND',
    'UNITED KINGDOM',
    'FRANCE',
    'ITALY',
    'TANZANIA',
    'SOUTH AFRICA',
    'MYANMAR',
    'KENYA',
    'SOUTH KOREA',
    'COLOMBIA',
    'SPAIN',
    'UGANDA',
    'ARGENTINA',
    'ALGERIA',
    'SUDAN',
    'UKRAINE',
    'IRAQ',
    'AFGHANISTAN',
    'POLAND',
    'CANADA',
    'MOROCCO',
    'SAUDI ARABIA',
    'UZBEKISTAN',
    'PERU',
    'ANGOLA',
    'MALAYSIA',
    'MOZAMBIQUE',
    'GHANA',
    'YEMEN',
    'NEPAL',
    'VENEZUELA',
    'MADAGASCAR',
    'CAMEROON',
    'COTE D IVOIRE',
    'NORTH KOREA',
    'AUSTRALIA',
    'NIGER',
    'SRI LANKA',
    'BURKINA FASO',
    'MALI',
    'ROMANIA',
    'MALAWI',
    'CHILE',
    'KAZAKHSTAN',
    'ZAMBIA',
    'GUATEMALA',
    'ECUADOR',
    'SYRIA',
    'NETHERLANDS',
    'SENEGAL',
    'CAMBODIA',
    'CHAD',
    'SOMALIA',
    'ZIMBABWE',
    'GUINEA',
    'RWANDA',
    'BENIN',
    'BURUNDI',
    'TUNISIA',
    'BOLIVIA',
    'BELGIUM',
    'HAITI',
    'CUBA',
    'SOUTH SUDAN',
    'DOMINICAN REPUBLIC',
    'CZECH REPUBLIC',
    'GREECE',
    'JORDAN',
    'PORTUGAL',
    'AZERBAIJAN',
    'SWEDEN',
    'HONDURAS',
    'UNITED ARAB EMIRATES',
    'HUNGARY',
    'TAJIKISTAN',
    'BELARUS',
    'AUSTRIA',
    'PAPUA NEW GUINEA',
    'SERBIA',
    'ISRAEL',
    'SWITZERLAND',
    'TOGO',
    'SIERRA LEONE',
    'LAOS',
    'PARAGUAY',
    'BULGARIA',
    'LIBYA',
    'LEBANON',
    'NICARAGUA',
    'KYRGYZSTAN',
    'EL SALVADOR',
    'TURKMENISTAN',
    'SINGAPORE',
    'DENMARK',
    'FINLAND',
    'CONGO',
    'SLOVAKIA',
    'NORWAY',
    'OMAN',
    'STATE OF PALESTINE',
    'COSTA RICA',
    'LIBERIA',
    'IRELAND',
    'CENTRAL AFRICAN REPUBLIC',
    'NEW ZEALAND',
    'MAURITANIA',
    'PANAMA',
    'KUWAIT',
    'CROATIA',
    'MOLDOVA',
    'GEORGIA',
    'ERITREA',
    'URUGUAY',
    'BOSNIA AND HERZEGOVINA',
    'MONGOLIA',
    'ARMENIA',
    'JAMAICA',
    'QATAR',
    'ALBANIA',
    'LITHUANIA',
    'NAMIBIA',
    'GAMBIA',
    'BOTSWANA',
    'GABON',
    'LESOTHO',
    'NORTH MACEDONIA',
    'SLOVENIA',
    'GUINEA-BISSAU',
    'LATVIA',
    'BAHRAIN',
    'EQUATORIAL GUINEA',
    'TRINIDAD AND TOBAGO',
    'ESTONIA',
    'TIMOR-LESTE',
    'MAURITIUS',
    'CYPRUS',
    'ESWATINI',
    'DJIBOUTI',
    'FIJI',
    'COMOROS',
    'GUYANA',
    'BHUTAN',
    'SOLOMON ISLANDS',
    'MONTENEGRO',
    'LUXEMBOURG',
    'SURINAME',
    'CABO VERDE',
    'MICRONESIA',
    'MALDIVES',
    'MALTA',
    'BRUNEI ',
    'BELIZE',
    'BAHAMAS',
    'ICELAND',
    'VANUATU',
    'BARBADOS',
    'SAO TOME & PRINCIPE',
    'SAMOA',
    'SAINT LUCIA',
    'KIRIBATI',
    'GRENADA',
    'ST. VINCENT & GRENADINES',
    'TONGA',
    'SEYCHELLES',
    'ANTIGUA AND BARBUDA',
    'ANDORRA',
    'DOMINICA',
    'MARSHALL ISLANDS',
    'SAINT KITTS & NEVIS',
    'MONACO',
    'LIECHTENSTEIN',
    'SAN MARINO',
    'PALAU',
    'TUVALU',
    'NAURU',
    'HOLY SEE'
]
